src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post-list'),
    path('<int:year>/<int:month>/', views.PostArchiveView.as_view(month_format='%m'), name="post-archive"),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
]

src/dalvtor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('root/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='blog:post-list', permanent=False), name='index'),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import gettext as _
from core.models import ModelBase


class Post(ModelBase):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    body = models.TextField()
    summary = models.TextField()
    tags = models.ManyToManyField('Tag', blank=True)

    class Meta:
        db_table = 'post'
        verbose_name = _('post')
        verbose_name_plural = _('posts')
        ordering = ('-created_at',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Tag(ModelBase):
    label = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        db_table = 'tag'
        verbose_name = _('tag')
        verbose_name_plural = _('tags')

    def __str__(self):
        return self.label

    def save(self, *args, **kwargs):
        self.slug = slugify(self.label)
        super().save(*args, **kwargs)

src/core/models.py
import uuid
from django.db import models


class ModelBase(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)

    class Meta:
        abstract = True
        ordering = ('-created_at',)

src/blog/forms.py
from django import forms
from django.utils.translation import gettext as _


class PostSearchForm(forms.Form):
    q = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': _('Search')}),
        required=False
    )

src/blog/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.dates import MonthArchiveView
from . import models
from . import forms


class PostListView(ListView):
    model = models.Post
    context_object_name = 'latest_posts'
    paginate_by = 20

    def get_queryset(self):
        filters = forms.PostSearchForm(self.request.GET)
        query = filters.data.get('q', '')
        tag = filters.data.get('t')
        queryset = models.Post.objects.filter(
            title__icontains=query,
        ).prefetch_related('tags')

        if tag:
            return queryset.filter(tags__slug__iexact=tag)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = models.Post.objects.all()
        context['tags'] = models.Tag.objects.all()
        return context


class PostArchiveView(PostListView, MonthArchiveView):
    queryset = models.Post.objects.all()
    date_field = "created_at"
    template_name = 'blog/post_list.html'


class PostDetailView(DetailView):
    model = models.Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

src/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block title %}{{ post.title }} - Dalvtor{% endblock %}
{% block metatags %}
    <meta property="title" content="{{ post.title|truncatechars:35 }}">
    <meta name="description" content="{{ post.summary|striptags|truncatechars:155 }}">
    <meta property="og:title" content="{{ post.title|truncatechars:35 }}">
    <meta property="og:url" content="{% url 'blog:post-list' %}">
    <meta property="og:description" content="{{ post.summary|striptags|truncatechars:155 }}">
    <meta property="og:type" content="article"/>
    <meta property="og:locale" content="en_US"/>
{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/github.min.css"
          integrity="sha256-iAmWN8uaUdN6Y9FCf8srQdrx3eVVwouJ5QtEiyuTQ6A=" crossorigin="anonymous"/>
{% endblock %}
{% block content %}
    {% load markdown_deux_tags %}
    <div>
        <div class="section-header align-middle">
            <svg class="inline-block" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                <path class="heroicon-ui"
                      d="M17 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6c0-1.1.9-2 2-2h2V3a1 1 0 1 1 2 0v1h6V3a1 1 0 0 1 2 0v1zm-2 2H9v1a1 1 0 1 1-2 0V6H5v4h14V6h-2v1a1 1 0 0 1-2 0V6zm4 6H5v8h14v-8z"></path>
            </svg>
             <span class="text-gray-900">{{ post.created_at|date:"F d, Y" }}</span>
        </div>
        {% if created_at != updated_at %}
            <div class="section-header">
                {{ post.updated_at|date:"F d, Y" }}
            </div>
        {% endif %}
        <h1 class="text-gray-900 font-bold text-3xl my-3">{{ post.title }}</h1>
        <div>
            {{ post.body|markdown }}
        </div>
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:post-list' %}?t={{ tag.slug }}" class="tag">
                {{ tag.label }}
            </a>
        {% endfor %}
    </div>

{% endblock %}
{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"
            integrity="sha256-1zu+3BnLYV9LdiY85uXMzii3bdrkelyp37e0ZyTAQh0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/django.min.js"
            integrity="sha256-+SyQpC5yv/bnTl7CGUx8a++ZwS99vK/MoedgZN4IaGI=" crossorigin="anonymous"></script>
    <script>
        hljs.configure({
            languages: ['python', 'html', 'django', 'shell'],
        });
        hljs.initHighlightingOnLoad();
    </script>
{% endblock %}

src/blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% block title %}Blog - Dalvtor{% endblock %}
{% block metatags %}
    <meta property="title" content="Dalvtor's blog">
    <meta name="description" content="My personal posts about programming, quotes, and different things">
    <meta property="og:title" content="Dalvtor's blog">
    <meta property="og:url" content="{% url 'blog:post-list' %}">
    <meta property="og:description" content="My personal posts about programming, quotes, and different things">
    <meta property="og:type" content="article"/>
    <meta property="og:locale" content="en_US"/>
{% endblock %}
{% block content %}
    {% load helpers %}
    {% load markdown_deux_tags %}
    <div class="flex-none md:flex">
        <div class="w-full md:w-3/4 pr-3">
            <ul>
                {% for post in latest_posts %}
                    <li>
                        <article class="mb-10">
                            <div class="section-header">
                                {{ post.created_at|date:"F d, Y" }}
                            </div>
                            <h1 class="post-title">
                                <a href="{% url 'blog:post-detail' post.slug %}">{{ post.title }}</a>
                            </h1>
                            <div class="post-summary">{{ post.summary|markdown }}</div>
                            {% for tag in post.tags.all %}
                                <a href="{% url 'blog:post-list' %}?t={{ tag.slug }}" class="tag">
                                    {{ tag.label }}
                                </a>
                            {% endfor %}
                        </article>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="w-full md:w-1/4">
            <div class="mb-10">
                <div class="section-header">
                    Archive
                </div>
                {% regroup posts by posted.year as year_list %}
                <ul>
                    {% for year in year_list %}
                        <li>
                            <div class="text-sm">{{ year.list.0.created_at|date:'Y' }} ({{ year.list|length }})</div>
                            {% regroup year.list by created_at.month as month_list %}
                            <ul>
                                {% for month in month_list %}
                                    <li>
                                        <a class="hover:text-indigo-500 ml-4 text-sm" href="{% url 'blog:post-archive' year.list.0.created_at|date:'Y' month.list.0.created_at|date:'m' %}">
                                            - {{ month.list.0.created_at|date:'F' }} ({{ month.list|length }})
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div>
                <div class="section-header">
                    Tags
                </div>
                {% for tag in tags %}
                    <a href="{% url 'blog:post-list' %}?t={{ tag.slug }}" class="tag">
                        {{ tag.label }}
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block metatags %}{% endblock %}
    {% load static %}
    <link href="{% static 'css/app.min.css' %}" rel="stylesheet">
    {% block styles %}
    {% endblock %}
</head>
<body>
{% include 'navbar.html' %}
<div class="container px-10 mx-auto">
    {% block content %}
    {% endblock %}
</div>
{% block scripts %}
{% endblock %}
</body>
</html>

src/templates/navbar.html
<nav class="flex items-center justify-between flex-wrap border-b mb-6 items-center">
    <div class="flex items-center justify-between flex-wrap py-2 container mx-auto px-10">
        <div class="flex items-center flex-shrink-0 mr-6">
            <a href="{% url 'index' %}" class="font-semibold text-xl hover:text-indigo-500">
                Dalvtor
            </a>
        </div>
        <div class="inline-block flex-grow flex items-center w-auto">
            <div class="text-sm flex-grow">
                <a href="{% url 'blog:post-list' %}" class="nav-link font-semibold">
                    Blog
                </a>
                <a href="{% url 'blog:post-list' %}" class="nav-link font-semibold">
                    About
                </a>
            </div>
            <div>
                <form class="w-full max-w-sm" action="{% url 'blog:post-list' %}">
                    <div class="flex items-center bg-gray-200 rounded focus">
                        <div class="flex-grow">
                            <label class="hidden" for="search">Search</label>
                            <input id="search"
                                   class="rounded bg-gray-200 w-full py-2 px-4 text-gray-800 focus:outline-none appearance-none"
                                   type="text" placeholder="Search" name="q" value="{{ request.GET.q }}"
                                   title="Search">
                        </div>
                        <div class="flex">
                            <button id="search-button"
                                    class="hover:bg-gray-400 focus:outline-none text-white font-bold py-2 px-3 rounded"
                                    type="submit"
                                    title="Search"
                                    role="button">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                                    <path class="heroicon-ui"
                                          d="M16.32 14.9l5.39 5.4a1 1 0 0 1-1.42 1.4l-5.38-5.38a8 8 0 1 1 1.41-1.41zM10 16a6 6 0 1 0 0-12 6 6 0 0 0 0 12z">
                                    </path>
                                </svg>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</nav>